name: user_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  another_stepper: ^1.2.2
  card_swiper: ^3.0.1
  customizable_counter: ^1.0.4
  dotted_line: ^3.2.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_otp_text_field: ^1.1.3+2
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  introduction_screen: ^3.1.14
  overlapped_carousel: ^1.0.2
  popover: ^0.3.0
  shared_preferences: ^2.2.3
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/images/introduction/
    - assets/images/socials/