name: user_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  card_swiper: ^3.0.1
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.3+2
  intl_phone_field: ^3.2.0
  introduction_screen: ^3.1.14
  page_transition: ^2.1.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/introduction/
    - assets/images/socials/