name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  file_picker: ^8.0.1
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.3+2
  flutter_stepindicator: ^0.1.7
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  intl_phone_field: ^3.2.0
  introduction_screen: ^3.1.14
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/introduction/
    - assets/images/socials/