name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  file_picker: ^8.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_otp_text_field: ^1.1.3+2
  flutter_polyline_points: ^2.0.0
  flutter_stepindicator: ^0.1.7
  flutter_svg: ^2.0.10+1
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  introduction_screen: ^3.1.14
  permission_handler: ^11.3.1
  provider: ^6.1.2
  razorpay_flutter: ^1.3.7
  shared_preferences: ^2.2.3
  sizer: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_signaturepad: ^25.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/images/introduction/
    - assets/images/socials/